Update README.md: Updated the documentation link
panoptic-labs/panoptic-v1-core pull request #4
Opened 2023-09-27 14:02 UTC by Aryan9592

New link seems to be this one -> https://panoptic.xyz/docs/intro

Also, there's a heading inside the README.md which says 'Force Exercisors'..Will it really be Exercisors? Or need to change it to 'Exercises'

2023-09-29 01:49 UTC, jesperkristensen58 requested changes
one comment - otherwise looks good

2023-09-29 01:49 UTC, jesperkristensen58 commented on README.md
> +- [Documentation](https://panoptic.xyz/docs/intro)
Let's use:

https://docs.panoptic.xyz

2023-09-29 03:43 UTC, Aryan9592 commented
What about that 'Force Exercisers'?

2023-09-30 17:39 UTC, dyedm1 commented
> What about that 'Force Exercisors'? 

This is intended - Just like liquidations and liquidators, exercises are actions while exercisors are actors. We use the same terminology internally and in our documentation.

LGTM on the other changes!

2023-09-30 17:40 UTC, merged

2023-09-30 17:40 UTC, Aryan9592 commented
Got it..Thanks!